-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    migration_id character varying(150) COLLATE pg_catalog."default" NOT NULL,
    product_version character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY (migration_id)
);

CREATE TABLE IF NOT EXISTS public.compensation_requests
(
    id serial NOT NULL,
    employee_id integer NOT NULL,
    work_date timestamp without time zone NOT NULL,
    hours_worked numeric(5, 2) NOT NULL,
    requested_compensation_date timestamp without time zone NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    requested_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    approved_by_id integer,
    decided_at timestamp without time zone,
    notes text COLLATE pg_catalog."default",
    tenant_id integer DEFAULT 1,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT compensation_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    id integer NOT NULL,
    "position" character varying(255) COLLATE pg_catalog."default",
    manager_id integer,
    tenant_id integer DEFAULT 1,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT employees_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.excel_uploads
(
    id serial NOT NULL,
    filename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    uploaded_by integer NOT NULL,
    uploaded_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    processed boolean DEFAULT false,
    error_message text COLLATE pg_catalog."default",
    tenant_id integer DEFAULT 1,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT excel_uploads_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.extra_hours
(
    id serial NOT NULL,
    employee_id integer NOT NULL,
    date timestamp without time zone NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    total_hours numeric(5, 2) NOT NULL,
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    notes text COLLATE pg_catalog."default",
    approved_by integer,
    approved_at timestamp without time zone,
    tenant_id integer DEFAULT 1,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT extra_hours_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.extra_hours_config
(
    id serial NOT NULL,
    diurnal_start time without time zone DEFAULT '06:00:00'::time without time zone,
    diurnal_end time without time zone DEFAULT '21:00:00'::time without time zone,
    diurnal_multiplier numeric(3, 2) DEFAULT 1.25,
    nocturnal_multiplier numeric(3, 2) DEFAULT 1.75,
    diurnal_holiday_multiplier numeric(3, 2) DEFAULT 2.00,
    nocturnal_holiday_multiplier numeric(3, 2) DEFAULT 2.50,
    weekly_extra_hours_limit integer DEFAULT 48,
    tenant_id integer DEFAULT 1,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT extra_hours_config_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.managers
(
    manager_id integer NOT NULL,
    department character varying(255) COLLATE pg_catalog."default",
    tenant_id integer DEFAULT 1,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT managers_pkey PRIMARY KEY (manager_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    role character varying(50) COLLATE pg_catalog."default" DEFAULT 'employee'::character varying,
    tenant_id integer DEFAULT 1,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.compensation_requests
    ADD CONSTRAINT compensation_requests_approved_by_id_fkey FOREIGN KEY (approved_by_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.compensation_requests
    ADD CONSTRAINT compensation_requests_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.employees (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT employees_id_fkey FOREIGN KEY (id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS employees_pkey
    ON public.employees(id);


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT employees_manager_id_fkey FOREIGN KEY (manager_id)
    REFERENCES public.managers (manager_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.excel_uploads
    ADD CONSTRAINT excel_uploads_uploaded_by_fkey FOREIGN KEY (uploaded_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.extra_hours
    ADD CONSTRAINT extra_hours_approved_by_fkey FOREIGN KEY (approved_by)
    REFERENCES public.managers (manager_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.extra_hours
    ADD CONSTRAINT extra_hours_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.employees (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.managers
    ADD CONSTRAINT managers_manager_id_fkey FOREIGN KEY (manager_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS managers_pkey
    ON public.managers(manager_id);

END;