-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Leads"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Phone" character varying(20) COLLATE pg_catalog."default",
    "Company" character varying(255) COLLATE pg_catalog."default",
    "Position" character varying(50) COLLATE pg_catalog."default",
    "Message" text COLLATE pg_catalog."default",
    "Source" character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'LANDING_FORM'::character varying,
    "Status" character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'NEW'::character varying,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ContactedAt" timestamp with time zone,
    CONSTRAINT "PK_Leads" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Payments"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Reference" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Status" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Amount" numeric(18, 2) NOT NULL,
    "CustomerEmail" character varying(255) COLLATE pg_catalog."default",
    "CustomerName" character varying(255) COLLATE pg_catalog."default",
    "WompiTransactionId" character varying(100) COLLATE pg_catalog."default",
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone,
    "Metadata" text COLLATE pg_catalog."default",
    "CustomerPhone" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."TenantModules"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TenantId" integer NOT NULL,
    "ModuleName" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Status" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "PurchasedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_TenantModules" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Tenants"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CompanyName" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Subdomain" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "IsActive" boolean NOT NULL,
    "ConnectionString" text COLLATE pg_catalog."default",
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Tenants" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TenantId" integer NOT NULL,
    "Email" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "FirstName" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "LastName" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "PasswordHash" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Role" character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'USER'::character varying,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS public.user_module_access
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    tenant_id integer NOT NULL,
    module_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_module_access_pkey PRIMARY KEY (id),
    CONSTRAINT user_module_access_user_id_module_name_key UNIQUE (user_id, module_name)
);

ALTER TABLE IF EXISTS public."TenantModules"
    ADD CONSTRAINT "FK_TenantModules_Tenants_TenantId" FOREIGN KEY ("TenantId")
    REFERENCES public."Tenants" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Users"
    ADD CONSTRAINT "FK_Users_Tenants_TenantId" FOREIGN KEY ("TenantId")
    REFERENCES public."Tenants" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Users_TenantId"
    ON public."Users"("TenantId");


ALTER TABLE IF EXISTS public.user_module_access
    ADD CONSTRAINT user_module_access_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public."Tenants" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_module_access_tenant_id
    ON public.user_module_access(tenant_id);


ALTER TABLE IF EXISTS public.user_module_access
    ADD CONSTRAINT user_module_access_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_module_access_user_id
    ON public.user_module_access(user_id);

END;